version: "3"

services: 
  server:
    build:
      context: server
    ports:
      - "3000:3000"
    volumes: 
      - ./server:/app
    command: >
      sh -c "npm start"
    environment:
      - SECRET_KEY=supersecretkey
      - PORT=3000
  
  client:
    build:
      context: client
    volumes: 
      - ./client:/app
    command: >
      sh -c "npm start"
    environment:
      - HOST=172.21.0.1
      - PORT=3000